export const ADD_LANDLORD = "ADD_LANDLORD";
export const RETRIEVE_LANDLORDS = "RETRIEVE_LANDLORDS";
export const UPDATE_LANDLORD = "UPDATE_LANDLORD";
export const DELETE_LANDLORD = "DELETE_LANDLORD";